services:
  # Backend API Service
  backend:
    container_name: pest_watch_backend
    image: pest_watch-backend:latest
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8098:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MAPSERVER_URL: http://mapserver:80/cgi-bin/mapserv
      MAPCACHE_URL: http://mapcache:80
    networks:
      - pest_watch_network

  # Frontend Web Service
  frontend:
    container_name: pest_watch_frontend
    image: pest_watch-frontend:latest
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8097:80"
    depends_on:
      - backend
    networks:
      - pest_watch_network

  # MapServer WMS Service
  mapserver:
    container_name: pest_watch_mapserver
    image: pest_watch-mapserver:latest
    build:
      context: .
      dockerfile: docker/mapserver.Dockerfile
    ports:
      - "8099:80"
    environment:
      MS_MAPFILE: /var/www/html/locust.map
      MS_ERRORFILE: /tmp/mapserver.log
      GDAL_CACHEMAX: 256
      GDAL_DISABLE_READDIR_ON_OPEN: YES
      CPL_VSIL_CURL_CACHE_SIZE: 200000000
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - pest_watch_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/cgi-bin/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MapCache Tile Service
  mapcache:
    container_name: pest_watch_mapcache
    image: pest_watch-mapcache:latest
    build:
      context: .
      dockerfile: docker/mapcache.Dockerfile
    ports:
      - "8100:80"
    environment:
      MAPCACHE_CONFIG: /etc/mapcache/mapcache.xml
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - mapcache_data:/var/cache/mapcache
    depends_on:
      mapserver:
        condition: service_healthy
    networks:
      - pest_watch_network

networks:
  pest_watch_network:
    driver: bridge

volumes:
  mapcache_data:
    driver: local